services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fire_extinguisher_backend
    env_file:
      - .env.development
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'redis-server', '--ping']
      interval: 10s
      timeout: 5s
      retries: 5  

  redis:
    image: redis:latest
    container_name: fire_extinguisher_redis
    ports:
      - '6379:6379'
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
